package ex_31_Exception;

public class Lab201_Throw {
    public static void main(String[] args) {

    }
    static  void DivideByZero (int a){

        if(a ==0);
        throw new ArithmeticException ("Error a == 0");

    }
}
